name: Build
on:
  push:
    branches:
      - mistress
  pull_request:

permissions:
  contents: read

concurrency: # Green Software Engineering Practices: https://github.com/Cambridge-ICCS/green-ci
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with: { persist-credentials: false }

      - uses: pnpm/setup@5d160c5bc68a09337ad0d5654e237e03253b5879 # v1
        with: { cache: true }

      - run: pnpm run build
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: dist
          path: dist

  vitest:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [18, 20, 22, 24, 26]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with: { persist-credentials: false }

      - uses: pnpm/setup@5d160c5bc68a09337ad0d5654e237e03253b5879 # v1
        with: { cache: true }

      - run: pnpm run test

  toml-test:
    needs: [build]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [18, 20, 22, 24, 26]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with: { go-version: stable }

      - run: go install github.com/toml-lang/toml-test/v2/cmd/toml-test@latest

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with: { persist-credentials: false }

      - uses: pnpm/setup@5d160c5bc68a09337ad0d5654e237e03253b5879 # v1
        with: { cache: true, install: false }

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: dist
          path: dist
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ${{ matrix.node }}
      - run: ./run-toml-test.bash
