name: Lint
on:
  push:
    branches:
      - mistress
  pull_request:

permissions:
  contents: read

concurrency: # Green Software Engineering Practices: https://github.com/Cambridge-ICCS/green-ci
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  zizmor:
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required for zizmor-action reporting
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with: { persist-credentials: false }

      - uses: zizmorcore/zizmor-action@6fc4b006235f201fdab3722e17240ab420d580e5 # v0.6.1
