name: Publish to NPM

on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            id-token: write  # Required for provenance and Trusted Publishing
            contents: read
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
            - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
            - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
              with:
                registry-url: 'https://registry.npmjs.org'
                node-version: 24
                cache: pnpm

            - run: pnpm install
            - run: pnpm build
            - run: pnpm publish --provenance --access public --no-git-checks
