name: Publish to NPM
on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

concurrency: # Green Software Engineering Practices: https://github.com/Cambridge-ICCS/green-ci
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-slim
    permissions:
      id-token: write # Required for provenance and Trusted Publishing
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with: { persist-credentials: false }

      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4
      - uses: pnpm/setup@5d160c5bc68a09337ad0d5654e237e03253b5879 # v1
      - run: just publish
